var topics = [
    "Authors of Cook Books",
    "Household Cleaners",
    "Space Shuttles",
    "Brand of Chips",
    "Songs with 'I' as the First Word of the Title",
    "Cosmetic Companies",
    "Book Publishers",
    "Christmas Traditions",
    "Genetic Traits",
    "Hospital Dramas",
    "Words or Phrases Containing the Word 'Snow'",
    "Actresses Who Have Played Bond girls",
    "Foods cooked on a Campfire",
    "Kind of Bears",
    "Floats in the Macy's Thanksgiving Day Parade",
    "Movies Starring Denzel Washington",
    "Energy Saving Practicies",
    "New Slang Words",
    "Artist Who Performed at Super Bowl Half-Time show",
    "Movies Where Characters get Drunk",
    "American Car Companies",
    "Foreign Car Companies",
    "Actors in the Fast and Furious Movies",
    "Movies that Begin with the Letter 'F'",
    "Marvel Characters",
    "DC Characters",
    "Monster Universer Monsters",
    "Famous Moments in Sports",
    "Athlete Who Play Themselves in a Movie",
    "Video Game Companies",
    "Creatures the Winchesters Hunt on Supernatural",
    "Famous Lawsuits",
    "Bestselling Authors",
    "Female Rappers",
    "Rappers with 'Lil' in their Stage Name",
    "Nicki Minaj Songs",
    "Shows that Take Place in the White House",
    "Dental Procedures",
    "Acronyms",
    "Kinds of Rice",
    "Tattoo Locations on the Body",
    "Comedians",
    "Christmas Movies",
    "Christmas Songs",
    "Scary Movies",
    "Brands of Chocolate",
    "Types of Candy",
    "Candy Brands",
    "Central American Countries",
    "Movies from the Current Year",
    "Phrases Containing the word 'Out'",
    "Things that you push",
    "Words that Begin with 'tri'",
    "Players who have wone Wimbledon",
    "Movies featuring Alien Attacks",
    "Greek Goodesses",
    "D9 Sorrorites/Fraternities",
    "New Year's Eve Traditions",
    "Shades of Blue",
    "Shades of Red",
    "Fruit with One Seed",
    "States",
    "Cities in Mississippi",
    "State Capitols",
    "Social Media Apps",
    "Cake Flavors",
    "Types of Pie",
    "Cookies",
    "Card Games",
    "Board Games",
    "Sports",
    "Famous Dous (ONLY 2",
    "Famous Singing Groups",
    "Vegetables",
    "Fruits",
    "Soda Flavors",
    "Fast Food Restaurants",
    "Chain restuarants",
    "Winter Accessories",
    "Names That Begin with the Letter 'A'",
    "Names That Begin with the Letter 'B'",
    "Names That Begin with the Letter 'M'",
    "Last Names",
    "Streaming Platforms",
    "Insects",
    "Types of Music",
    "Musical Instruments",
    "Holidays",
    "Pizza Toppings",
    "Types of Sandwhiches",
    "Food to Serve for Thanksgiving",
    " Movies or Shows starring Angela Basset",
    "HBCUs",
    "Thing Invented by African Americans",
    "Game Shows",
    "Deli Meats",
    "2 Sylablle Words",
    "3 Sylablle Words",
    "Activities to do in the Snow",
    "Another word for Money",
    "Soups",
    "Banks",
    "Types of Flowers",
    "Breakup Songs",
    "Purple Foods",
    "Movie Remakes",
    "Foods Names After Places",
    "Breakfast Cereals",
    "College Bowl Games",
    "NFL Teams",
    "NBA Teams",
    "String Instruments",
    "Wood Instruments",
    "TV Doctors",
    "Muscles in the Human Body",
    "Members of the Royal Family",
    "Theme Songs",
    "Sports that don't require a Ball",
    "Horror Movie Monsters",
    "Disney Princesses",
    "Breakfast Foods",
    "Fashion Brands",
    "Types of Bread",
    "National Monuments",
    "Famous Landmarks",
    "TV Channels",
    "Famous American Idol Contestants",
    "Harry Potter Characters",
    " Walking Dead Characters",
    "Office Supplies",
    "Hot Drinks",
    "Flavors of Ice Cream",
    "Grocery Stores",
    "Black Sitcomes",
    "Female R&B Singers",
    "Male R&B Singers",
    "Quaterbacks (Past and Present)",
    "Beyonce Songs",
    "Presidents of the United States"
];

var dares = [
    "Do A Mickey Mouse impression", 
    "Prank Call A Friend",
    "Act Like a Monkey for 15 seconds",
    "Count backwards for 45",
    "Ask neighbor for some a cup of sugar",
    "Sing a silly song",
    "Do 15 Jumping Jacks",
    "Keep Your Eyes Closed for 1 full minute",
    "Take a bite of a stick of better",
    "Talk with your tongue out for 1 minute",
    "Do an impression of the person that said you were lying",
    "Eat a teaspoon of butter",
    "Lick your elbow while reciting the alphabet",
    ""

]

function generateRandomTopic() {
    var randomTopic = Math.floor(Math.random() * topics.length);
    document.getElementById("topic").innerText = topics[randomTopic];
}

function startGame(){
    console.log("Game Started");
    document.getElementById("startButton").classList.add('hidden');
    document.getElementById('rulesDiv').classList.add('hidden');
    document.getElementById("ikylButton").classList.add('show');
}